/* eslint-disable max-len */
/**
 * Message Listener to insult people using old.reddit links
 *
 * Please don't take this too seriously
 */

// Source: https://gist.github.com/HBIDamian/7791dcbbf3f92e0ce252a9ca3bcb7800
const insults = ["A small dick's like a disability, so I won't make fun of you.",
  'After Covid is fully over, please carry on wearing your face mask so I do not have to look at you!', "All right. All right, I'll confess… I confess you're a bigger idiot than I thought you were.",
  'As an outsider, what do you think of the human race?', 'At least Hitler killed himself.', "At least there's one good thing about your body. It isn't as ugly as your face.",
  "At least when I do a handstand my stomach doesn't hit me in the face.",
  "Aww, it's so cute when you try to talk about things you don't understand.",
  'Beauty is skin deep, but ugly is to the bone.', "Being a dick to everyone won't make yours any bigger.",
  "Behind every fat person there is a beautiful person. No seriously, you're in the way.",
  "Brains aren't everything, in fact in your case their nothing.",
  "Brains aren't everything. In your case they're nothing.",
  'Calling you an idiot would be an insult to all stupid people.', 'Did God design you from the leftover pieces in a trash can?', 'Did you forget to brush your teeth? Your breath stinks!', 'Do your keepers a huge favour: do a triple summersault through the air, and disappear up your own asshole.', "Don't be ashamed of who you are. That's your parent's job.",
  "Don't feel sad, don't feel blue, Frankenstein was ugly too.",
  "Don't you have a terribly empty feeling - in your skull?",
  "Don't you need a license to be that ugly?",
  'Earth is full! Go home!', 'Eat shit and live!', "Even among idiots, you're lacking.",
  "Even the shower doesn't want to see you.",
  "Everyone's entitled to be stupid, but you're abusing the privilege",
  'Everything that comes out of your mouth is a lie, everything that goes in is a poop.', "Fake hair, fake nails, fake smile. Are you sure you weren't made in China?",
  'Filth! Scum! A by-product of dirt and vileness!', "Fuck you, you're ugly.",
  'Funny little thing, your brain! How do you get around in that thing?', "Gay? I'm straighter than the pole your mom dances on.",
  'Go and hide under something old!', 'Go away! I was looking at something better than you!', 'Go polish your crocs.', 'God made you as an example of what not to do.', 'Good story, but in what chapter do you shut the fuck up?', 'Grab a straw, because you suck!', "Hang on, I'm still trying to decide whether I don't give a shit, or if I don't give a fuck!",
  "Hey, train wreck! This isn't your station!",
  'Hey, you have something on your chin. No, the 3rd one down.', 'How about you get lost in the ocean instead?', 'How did you get here? Did someone leave your cage open?', "How many wrinkles does an asshole have? Smile! I'll count them!",
  "How old are you? - Wait I shouldn't ask, you can't count that high.",
  'I bet you wear a nose ring because no one wants to put one on your finger.', 'I bet your brain feels as good as new, seeing that you never use it.', 'I burst my pimples at you and call your door-opening request a silly thing, you tiny-brained wipers of other people’s bottoms!', "I can't help imagining how much awesome the world would be if your dad had just pulled out.",
  'I could eat a bowl of alphabet soup and poop out a smarter statement than whatever you just said.', "I could get on your level, but I don't like being on my knees as much as you do!",
  'I do desire that we may be better strangers.', "I don't engage in mental combat with the unarmed.",
  "I don't exactly hate you, but if you were on fire and I had water, I'd drink it.",
  "I don't know what your problem is, but I'll bet it's hard to pronounce.",
  'I don’t want to talk to you no more, you empty-headed animal food trough wiper! I fart in your general direction! Your mother was a hamster and your father smelt of elderberries!', "I failed a spelling test because they asked me how to spell 'bitch' and I wrote down your name.",
  'I guess you prove that even god makes mistakes sometimes.', "I haven't seen you run that fast since Twinkies went on sale!",
  'I hear when you were a child your mother wanted to hire somebody to take care of you, but the mafia wanted too much.', 'I heard you received a brain transplant but it rejected your body.', 'I hope one day you choke on the shit you talk!', 'I hope you step on legos', 'I hope your next blowjob is from a shark!', 'I hope your next period happens in a shark tank!', 'I in no way advocate violence... but sometimes, a slap is worth a thousand words.', 'I just stepped in something that was smarter than you and smelled better too.', "I know You're not as stupid as you look, Nobody could be!",
  "I love what you've done with your hair. How do you get it to come out of your nostrils like that?",
  'I see you were so impressed with your first chin that you added two more.', "I set my standards pretty low, so I'm never disappointed.",
  "I think it's mating season at the zoo, so go back to the orangutans and get married!",
  'I thought of you today. It reminded me to take the garbage out.', 'I throw up when I look at you!', 'I was pro-life. Then I met you.', "I was today years old when I realized I didn't like you.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  'I wish I bleached my eyes before I saw your face!', "I would ask how old you are, but I know you can't count that high.",
  'I would burn you but burning trash is bad for the environment.', "I would never date you. I'm lonely, not desperate.",
  'I would slap you, but shit splatters!', "I'd agree with you but then we'd both be wrong.",
  "I'd give you a nasty look but you've already got one.",
  "I'd like to kick you in the teeth but why improve your looks?",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "I'd offer you some gum but your smiles got plenty of it.",
  "I'd prefer a battle of wits, but you appear unarmed.",
  "I'd say you're funny, but looks aren't everything.",
  "I'd slap you, but that would be animal abuse.",
  "I'd tell you to go stuff yourself, but that would be cruel and unusual punishment.",
  "I'd tell you to go to hell, but I work there and don't want to see you every day.",
  'If assholes could fly, this place would be an airport!', "If brains were gold, you'd be poorer than a homeless person!",
  "If I had a dollar for every time you said something smart, I'd be broke.",
  "If I had a face like yours, I'd sue my parents.",
  'If I throw a stick, would you leave?', 'If I told you that I have a piece of dirt in my eye, would you move?', "If I wanted a bitch I'd have bought a dog.",
  "If I wanted to hear from an asshole, I'd fart.",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "If I wanted to listen to an asshole, I'd fart.",
  'If I were your mirror I would commit suicide.', "If I'm ever in need of advice from a psychotic potato dwarf, you'll be the first to know.",
  'If laughter is the best medicine, your face must be curing the world.', 'If my dog had your face I would shave his ass and teach him to walk backwards.', 'If the human body is 75% water, how can you be 100% salt?', "If there was a vote for 'least likely to succeed' you'd win first prize.",
  "If you don't think I ain't makin' a mental list of all your fuckin' bullshit...",
  "If ugly were a crime, you'd get a life sentence.",
  'If you have a problem with me, write the problem on a piece of paper, fold it, and shove it up your ass.', 'If you were anymore inbred, you would make a sandwich!', "If you were the trophy at the end of the race, I'd run backwards!",
  "If you were twice as smart, you'd still be stupid!",
  'If your IQ was multiplied by anything it would still be 0.', 'If your parents were to divorce, would they still be brother and sister?', 'If your ugliness was measured in bricks, you would own The Great Wall of China', "If you're gonna be a smartass, first you have to be smart. Otherwise, you're just an ass.",
  'If your gonna be two faced, honey at least make one of them pretty.', "I'll never forget the first time we met. But I'll keep trying.",
  "I'm jealous of all the people who haven't met you!",
  "I'm jealous of people that don't know you!",
  "I'm not a photographer, but I can picture you better elsewhere",
  'I’m not about to take advice from someone who looks like they cry when McDonald’s forgets to give them sauce with their 20 nug', "I'm not questioning your honour. I'm denying its existence.",
  "I'm sorry, I couldn't hear you over the little voice in my head screaming 'What a load of rubbish!'",
  "I'm sorry your dad beat you instead of cancer.",
  "I'm surrounded by idiots... Or, wait, that's just you.",
  'Is it sad that your theme song might as well have a 0/0 signature?', 'Is it true when you were born the doctor turned around and slapped your mother?', 'Is that your face? Or did your neck just throw up?', 'Is your butt jealous of the amount of shit that just came out of your mouth?', 'It looks like your face caught fire and someone tried to put it out with a hammer.', "It's better to let someone think you are an idiot than to open your mouth and prove it.",
  "It's not pretty watching a jackass trying to eat a pomegranate.",
  "Jesus might love you, but everyone else thinks you're an idiot.",
  "Just Because You Have The Emotional Range Of A Teaspoon Doesn't Mean We All Have!",
  "Just because you have one doesn't mean you have to act like one.",
  "Keep rolling your eyes. Maybe you'll find a brain back there!",
  'Life is full of disappointments and I just added you to the list.', "Look, you aren't funny. Your life is just a joke.",
  'May both sides of your pillow be uncomfortably warm.', 'May your wife give birth to a centipede so you have to work for shoes all your life.', "Mirrors can't talk, and lucky for you they can't laugh either.",
  'My middle finger salutes you!', "My psychiatrist told me I was crazy and I said I want a second opinion. He said okay, you're ugly too.",
  'Nice shirt, what brand is it? Clearance?', "No, I checked my receipt. I didn't buy any of your bullshit!",
  "N'Sync said it best, “BYE, BYE, BYE!”",
  'Of course I talk like an idiot, how else would you understand me?', 'Oh go on. Crack a smile. I want to see if your eyebrows drop off!', 'Oh, what? Sorry. I was trying to imagine you with a personality.', "Okay, chopzilla, listen up, 👍 This little piggy went to the market. ☝️ This little piggy stayed home... 🖕 And if this little piggy doesn't shut the fuck up, I'm gonna shove my foot up your fucking ass",
  "One more wrinkle and you'd pass for a prune.",
  'Out of 100,000 sperm, you were the fastest?', 'People clap when they see you. They clap their hands over their eyes!', "Please, I could remove 90% of your 'beauty' with a tissue!",
  'Remember to look both ways before you go fuck yourself!', 'Roses are red violets are blue, God made me pretty, what happened to you?', "Roses are red, I don't give a fuck! Your mum and dad are fucking crazy for having you, ya fucking spunk bubble. Shut up!",
  'Roses are red, poo is brown, shut the fuck up, and sit the fuck down.', "Roses are red, violets are blue. I can't wait to punch you...",
  "Save your breath - you're going to need it to blow up your date.",
  'Shock me, say something intelligent.', "Shut up, you'll never be the man your mother is!",
  'Shut up. Just... shut up...', 'So tell me... Is your ass aware that your head has moved in?', 'Some babies were dropped on their heads but you were clearly thrown at a wall.', 'Some cause happiness wherever they go; others whenever they go.', 'Someday you will go far, and I hope you stay there.', "Someone once said You're pretty as a picture... I agree I would love to hang you.",
  'Somewhere out there is a tree working very hard to replace the oxygen you consume. Now go apologize to it!', 'Somewhere, somehow, you are robbing a village of their idiot.', "Sorry I didn't get that, I don't speak idiot.",
  "Sorry, I can't hear you over how annoying you are.",
  'Stupidity is not a crime so you are free to go.', "Sure, I've seen people like you before - but I had to pay an admission.",
  'Suck Devilcock in hell!', "Tell your mom to make your mac n cheese, I'll be home soon.",
  "The 80's called, they want their haircut back.",
  "The clothes you wear are so ugly even a scarecrow wouldn't wear them.",
  'The last time I saw a face like yours I fed it a banana.', 'The last time I saw something like you, I flushed it!', 'The next word that comes out of your mouth better be some brilliant fuckin Mark Twain shit cause everything else so far sucked harder than my hoover!', 'The only accessory that could save your outfit is an invisibility cloak!', 'The only positive thing about you is your HIV status.', 'The only reason your partner likes you is because they were taught to enjoy the little things in life.', "The only thing that goes erect when I'm near you is my middle finger.",
  "The zoo called. They're wondering how you got out of your cage.",
  "They say people get what they deserve. In your case, it's a participation trophy.",
  'Thou art as fat as butter!', 'Twatface!', 'Twinkle twinkle little star, I want to hit you with my car, Throw you off a cliff so high, I hope you break your neck and die.', "Twinkle twinkle little star, You're the  nastiest thing so far!",
  "Twinkle Twinkle little star, you're the ugliest I've seen so far!",
  "Twinkle twinkle little whore, close your legs, they're not a door.",
  "U. G. L. Y. You ain't got no alibi, you ugly! Eh! Hey! You ugly!",
  "Was one of your parents, a Naked Mole Rat? You're ugly as fuck!",
  'We all sprang from apes, but you did not spring far enough.', "What doesn't kill you, disappoints me...",
  'What the fucking hell are you, you great gangly fuck-knuckle twat, greasy-haired cunt bag. Fuck you.', "What's the difference between you and an egg? Eggs get laid!",
  "When I see your face there's not a thing I would change... Except for the direction I'm walking in.",
  'When the airforce needs extra landing space they should just rent out your forehead.', 'When you look in the mirror, say hi to the clown you see in there for me, would ya?', 'When you were born your mom threw you out the window and the window threw you back.', 'When you were born, the police arrested your dad, the doctors slapped your mum, animal control euthanized your sibling, and A&E made a documentary that saved your life.', 'When you were born, the police said you were a piece of shit. They shot you.', 'Who lit the fuse on your tampon?', "Why don't you check up on eBay and see if they have a life for sale!",
  'Why is it acceptable for you to be an idiot, but not for me to point it out?', "Wipe your mouth, there's still a tiny bit of bullshit around your lips.",
  'With a face like yours, I wish I was blind!', "Yo Mama's got a baldy head and collects fotty stickers!",
  'You are an insult upon insults of a booble of an assortment.', "You are like a cloud. When you disappear, it's a beautiful day.",
  'You are living proof that manure can sprout legs and walk.', 'You are the human version of period cramps.', 'You bring everyone so much joy... when you leave the room.', 'You conserve toilet paper by using both sides.', 'You dense, irritating, miniature beast of a burden!', "You do realize makeup isn't going to fix your stupidity?",
  'You foul, loathsome, evil little cockroach!', 'You have Diarrhea of the mouth; constipation of the ideas.', 'You have the charisma of a damp towel.', 'You have the charm of a dead battery.', 'You have the kinds of looks that make people talk about your personality.', 'You have the memory of a goldfish, only less useful.', 'You have the perfect face for radio.', 'You have the subtlety of a brick and the depth of a shot glass!', 'You know, you are a classic example of the inverse ratio between the size of the mouth and the size of the brain.', 'You look like a before picture.', 'You look like a rock smashed into a pile of sand, rolled into a blunt, and got smoked through an asthma inhaler.', 'You look like the after picture of a meth ad.', 'You look like the result of pressing random on the character creation menu.', "You may look like an idiot and talk like an idiot but don't let that fool anyone. You're really is an idiot.",
  "You must have been born on a highway because that's where most accidents happen.",
  "You only annoy me when you're breathing.",
  'You prefer three left turns to one right turn.', 'You remind me of a penny. Two-faced, and not worth much!', 'You should introduce your upper lip to your lower lip sometime, and shut the fuck up!', 'You should use gorilla glue instead of a chapstick!', 'You should wear a muzzle. No reason.', "You shouldn't play hide and seek, no one would look for you.",
  'You walk behind your boss reaching through his legs and supporting his testicles.', 'You were so ugly that when you were born the doctor put tinted windows on your incubator.', "You'd be suicidal if you felt as bad as you look.",
  "You'll never be the man your mother is.",
  'Your advice is about as useful as a paper-mache bomb shelter.', 'Your birth certificate is an apology letter from the condom factory.', 'Your body fat is about as evenly distributed as wealth in the US economy.', "Your brain's so minute that if a hungry cannibal cracked your head open, there wouldn't be enough to cover a small water biscuit.",
  'Your face could scare the shit out of a toilet.', 'Your face looks like something I would draw with my non-dominant hand.', 'Your face makes onions cry.', 'Your family tree must be a cactus because everyone on it is a prick.', 'Your head shape looks like a broken condom.', "Your intelligence is like a black hole, it's non-existent.",
  'Your IQ is lower than the Mariana Trench.', 'Your jokes are like your personality, dry and lacking substance.', "Your lips keep moving but I don't speak stupid.",
  'Your mother mates with reindeer!', 'Your mother must have a really loud bark!', 'Your mother was a hamster and your father smelt of elderberries.', 'Your mum is so fat, she has to wear 2 watches because she covers two time zones!', 'Your parents hated you so much your bath toys were an iron and a toaster!', "Your parents must be siblings, that's the only explanation for your genetic malfunction.",
  "Your personality is like a train wreck - everyone wants to look away, but can't help but watch.",
  'Your secrets are always safe with me. I never even listen when you tell me them.', 'Your sense of humor is so dry, you make the Sahara look like a water park.', "Your value doesn't even amount to the juice squeezed from an old whore's soiled tampon!",
  'Your voice is like a car alarm going off!', "You're a failed abortion whose birth certificate is an apology letter from the condom factory.",
  "You're a fucking idiot.",
  "You're a grey sprinkle on a rainbow cupcake!",
  "You're a knob-munching bumblefuck.",
  "You're about as useful as a phone with no batteries.",
  "You're as beautiful as a pig in a mud bath!",
  "You're as beautiful as dog shit!",
  "You're as bright as a black hole and twice as dense!",
  "You're as clumsy as a bull in a china shop.",
  "You're as focused as a squirrel on caffeine.",
  "You're as graceful as a hippopotamus on roller skates.",
  "You're as predictable as a sunrise, but not nearly as pleasant.",
  "You're as ugly as Jason Voorhees in 'Friday The 13th Part 8: Jason Takes Manhattan'!",
  "You're as useful as an ashtray on a motorcycle.",
  "You're as useless as a logitech controller in a submarine!",
  "You're happy to believe in something that's invisible, but if it's staring you in the face, nope, can't see it. There's a scientific explanation for that: you're thick.",
  "You're kind of like Rapunzel except instead of letting down your hair, you let down everyone in your life.",
  "You're like a cloud, when you go away the day gets brighter",
  "You're like a light switch, even a little kid can turn you on.",
  "You're like dobby from Harry Potter, only people won't be sad when you die in the seventh book.",
  "You're like Mondays, everyone hates you.",
  "You're like school in July. No class.",
  "You're like STDs, nobody wants you, everyone hates you and it proves your parents should have used protection.",
  "You're like the human version of a headache!",
  "You're like the type of person to spoil a movie before someone watches it, no one likes you.",
  "You're my favourite! You are the best, you know why? Cause you're so thick! You're mister thick thickity thick face from thicktown thickannia. And so is your Dad!",
  "You're not a model. You're a bitch with a smart phone and 37 editing apps. Shut the fuck up!",
  "You're not as bad as people say, you are much, much worse.",
  "You're not completely useless, you can always serve as a bad example.",
  "You're not worth roasting.",
  "You're not yourself today, I noticed the improvement immediately.",
  "You're proof evolution can go in reverse.",
  "You're proof that God has a sense of humour.",
  "You're so boring, even your shadow leaves you to go do something more exciting.",
  "You're so boring, you make paint drying look like a thrilling experience.",
  "You're so dumb that you got hit by a parked car.",
  "You're so dumb you make Kim Kardashian seem smart!",
  "You're so dumb, your dog teaches you tricks.",
  "You're so fake, even Barbie is jealous!",
  "You're so fake, even China rejected your knockoff version.",
  "You're so fat the only letters of the alphabet you know are KFC.",
  "You're so fat you could sell shade.",
  "You're so fat you need cheat codes to play Wii Fit.",
  "You're so fat, that you have your own gravitational pull!",
  "You're so fat, you make the galaxy look like it's on the molecular scale.",
  "You're so fat, you need cheat codes to play Wii Fit!",
  "You're so forgetful, you need GPS to find your own memory.",
  "You're so foul, even the flies stay away from your stench.",
  "You're so slow, time waits for you like a polite stranger waiting for a bus.",
  "You're so slow, you make a snail look like Usain Bolt.",
  "You're so stupid I don't have the time or the crayons to explain this to you.",
  "You're so stupid you tried to wake a sleeping bag.",
  "You're so stupid, you thought Dunkin' Donuts was a basketball Team!",
  "You're so stupid, it takes you an hour to cook minute rice.",
  "You're so stupid, you'd trip over a cordless phone.",
  "You're so stupid. That's just it really. I got nothing else to add.",
  "You're so ugly that when your own mother dropped you off at school she got a fine for littering!",
  "You're so ugly, Hello Kitty said goodbye to you!",
  "You're so ugly, that when you popped out the doctor said 'Aww what a treasure', and your mom said 'Yeah let's bury it'",
  "You're so ugly, that your own mother didn't even turn up to your birth!",
  "You're so ugly, when you got robbed, the robbers made you wear their masks.",
  "You're so ugly, when you look in the mirror, your reflection looks away.",
  "You're so ugly, when you threw a boomerang it didn't come back.",
  "You're so ugly, when your mum dropped you off at school, she got a fine for littering!",
  "You're so ugly, you make blind kids cry.",
  "You're so ugly, you make blind people wish they were deaf too.",
  "You're so ugly, you make onions cry.",
  "You're so ugly, you scared the crap out of the toilet.",
  "You're so ugly, your brain would fit in a candy cane.",
  "You're so ugly, your face makes the news look good.",
  "You're so ugly, your mother would run for the door if she saw you.",
  "You're so ugly, your mother would throw you in the water with a stone.",
  "You're so unoriginal, you make a copy machine look like a creative genius.",
  "You're the equivalent to a piece of shit at the bottom of my shoe!",
  "You're the kind of person who could make a therapist need therapy.",
  "You're the kind of person who could suck the fun out of a bouncy castle.",
  "You're the reason the gene pool needs a lifeguard.",
  "You're the reason they invented double doors!",
  "You're the reason why protection exists!",
  "You're the reason your dad drinks.",
  "You're the reason your nan gets bullied at bingo!",
  "You're the result of searching for yourself on Wish.com!",
  "You're what the French call: 'Les incompetents'.",
  "You've got less meat in your pants than there is in a vegetarian restaurant.",
  "I'll speak to you in a language you understand: \"Idiot you are!\"",
  'Repeat after me: "I am dumb!"', "When you were born, the doctor came out to the waiting room and said to your dad, \"I'm very sorry. We did everything we could. But he pulled through.\"",
  'You stare at frozen juice cans because they say, "concentrate".', 'Yo Mama so fat she sued Xbox 360 for guessing her weight.', "You're so fat that when you were diagnosed with a flesh eating bacteria - the doctors gave you 87 years to live.",
  "You're so fat you've got more chins than a Hong Kong phone book.",
  "Yo Mama so fat she's on both sides of the family.",
  "Yo Mama so fat that even Dora couldn't explore her.",
  "Yo Mama so fat that she doesn't need the internet; she's already world wide.",
  "You're so fat that when you farted you started global warming.",
  "You're so fat the back of your neck looks like a pack of hot-dogs.",
  "You're so fat that when you fell from your bed you fell from both sides.",
  "You're so fat when you get on the scale it says \"To be continued.\"",
  "You're so fat when you go swimming the whales start singing \"We Are Family\".",
  "You're so fat when you stepped on the scale, Buzz Lightyear popped out and said \"To infinity and beyond!\"",
  "You're so fat when you turn around, people throw you a welcome back party.",
  "You're so fat when you were in school you sat by everybody.",
  "You're so fat when you went to the circus the little girl asked if she could ride the elephant.",
  "You're so fat when you go on an airplane, you have to pay baggage fees for your ass.",
  "You're so fat whenever you go to the beach the tide comes in.",
  "You're so fat I could slap your butt and ride the waves.",
  "You're so fat I'd have to grease the door frame and hold a Twinkie on the other side just to get you through.",
  'Yo Mama so dumb I told her Christmas was around the corner and she went looking for it.', "You're so dumb it took you 2 hours to watch 60 minutes.",
  'Yo Mama so dumb she bought tickets to Xbox Live.', "You're so dumb that you thought The Exorcist was a workout video.",
  "You're so ugly that you went to the salon and it took 3 hours just to get an estimate.",
  "You're so ugly that even Scooby Doo couldn't solve that mystery.",
  "What is the weighted center between Planet X and Planet Y? Oh it's YOU!",
  ':eggplant: :eggplant: :eggplant:', "I'm jealous of all the people that haven't met you.",
  "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
  "You're so ugly, when your mom dropped you off at school she got a fine for littering.",
  'You bring everyone a lot of joy, when you leave the room.', "What's the difference between you and eggs? Eggs get laid and you don't.",
  "You're as bright as a black hole, and twice as dense.",
  "I tried to see things from your perspective, but I couldn't seem to shove my head that far up my ass.",
  "Two wrongs don't make a right, take your parents as an example.",
  "You're so ugly, when you popped out the doctor said \"Aww what a treasure\" and your mom said \"Yeah, lets bury it.\"",
  'I have neither the time nor the crayons to explain this to you.', 'You have two brains cells, one is lost and the other is out looking for it.', 'How many times do I have to flush to get rid of you?', 'Some drink from the fountain of knowledge; you only gargled.', "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  'Somewhere out there is a tree, tirelessly producing oxygen so you can breathe. I think you owe it an apology.', "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  'Which sexual position produces the ugliest children? Ask your mother.', 'If you really want to know about mistakes, you should ask your parents.', "If I gave you a penny for your thoughts, I'd get change.",
  'If I were to slap you, it would be considered animal abuse.', 'Do you know how long it takes for your mother to take a crap? Nine months.', 'What are you going to do for a face when the baboon wants his butt back?', "Well I could agree with you, but then we'd both be wrong.",
  "You're so fat, you could sell shade.",
  'It looks like your face caught on fire and someone tried to put it out with a hammer.', "You're not funny, but your life, now that's a joke.",
  'Oh my God, look at you. Was anyone else hurt in the accident?', 'What are you doing here? Did someone leave your cage open?', "You're so ugly, the only dates you get are on a calendar.",
  "I can explain it to you, but I can't understand it for you.",
  'You are proof that God has a sense of humor.', "If you spoke your mind, you'd be speechless.",
  "Why don't you check eBay and see if they have a life for sale.",
  "You're so fat you need cheat codes to play Wii Fit",
  'Do you still love nature, despite what it did to you?', 'You are proof that evolution CAN go in reverse.', "I'll never forget the first time we met, although I'll keep trying.",
  'Your parents hated you so much your bath toys were an iron and a toaster', "It's kinda sad watching you attempt to fit your entire vocabulary into a sentence.",
  'I fart to make you smell better.', "You're so ugly you make blind kids cry.",
  "You're a person of rare intelligence. It's rare when you show any.",
  "You're so fat, when you wear a yellow rain coat people scream ''taxi''.",
  'I heard you went to a haunted house and they offered you a job.', "If your brain was made of chocolate, it wouldn't fill an M&M.",
  'I heard your parents took you to a dog show and you won.', 'Am I getting smart with you? How would you know?', "We all sprang from apes, but you didn't spring far enough.",
  "I'm no proctologist, but I know an asshole when I see one.",
  'When was the last time you could see your whole body in the mirror?', 'You must have a very low opinion of people if you think they are your equals.', 'So, a thought crossed your mind? Must have been a long and lonely journey.', "You're the best at all you do - and all you do is make people hate you.",
  'Looks like you fell off the ugly tree and hit every branch on the way down.', "Looks aren't everything; in your case, they aren't anything.",
  'You have enough fat to make another human.', "You're so fat a picture of you would fall off the wall!",
  "Your hockey team made you goalie so you'd have to wear a mask.",
  'Ordinarily people live and learn. You just live.', 'Did your parents ever ask you to run away from home?', 'I heard you took an IQ test and they said your results were negative.', "You're so ugly, you had tinted windows on your incubator.",
  "I'm not saying you're fat, but it looks like you were poured into your clothes and someone forgot to say \"when\"",
  "I've seen people like you, but I had to pay admission!",
  "I hear the only place you're ever invited is outside.",
  "Keep talking, someday you'll say something intelligent!",
  "You couldn't pour water out of a boot if the instructions were on the heel.",
  "Even if you were twice as smart, you'd still be stupid!",
  "You're so fat, you have to use a mattress as a maxi-pad.",
  "I may be fat, but you're ugly, and I can lose weight.",
  'I was pro life before I met you.', "What's the difference between you and Hitler? Hitler knew when to kill himself.",
  "You're so fat, your double chin has a double chin.",
  'If ignorance is bliss, you must be the happiest person on earth.', "You're so ugly you have to trick or treat over the phone.",
  "I'd hit you but we don't hit girls around here.",
  'Dumbass.', 'Bitch.', "If I wanted a bitch, I'd have bought a dog.",
  'Scientists say the universe is made up of neutrons, protons and electrons. They forgot to mention morons.', 'Why is it acceptable for you to be an idiot but not for me to point it out?', 'Did you know they used to be called "Jumpolines" until your mum jumped on one?', "You're not stupid; you just have bad luck when thinking.",
  "I'm sorry I didn't get that - I don't speak idiot.",
  'Hey, your village called – they want their idiot back.', 'I just stepped in something that was smarter than you… and smelled better too.', "You're so fat that at the zoo the elephants started throwing you peanuts.",
  "You're so fat every time you turn around, it's your birthday.",
  "You're so fat your idea of dieting is deleting the cookies from your internet cache.",
  "You're so fat your shadow weighs 35 pounds.",
  "You're so fat I could tell you to haul ass and you'd have to make two trips.",
  "You're so fat I took a picture of you at Christmas and it's still printing.",
  "You're so fat I tried to hang a picture of you on my wall, and my wall fell over.",
  "You're so fat Mount Everest tried to climb you.",
  "You're so fat you can't even jump to a conclusion.",
  "You're so fat you can't fit in any timeline.",
  "You're so fat you can't fit in this joke.",
  "You're so fat you don't skinny dip, you chunky dunk.",
  "You're so fat you fell in love and broke it.",
  "You're so fat you go to KFC and lick other peoples' fingers.",
  "You're so fat you got arrested at the airport for ten pounds of crack.",
  "You're so fat you'd have to go to Sea World to get baptized.",
  "You're so fat you have your own zip code.",
  "You're so fat you have more rolls than a bakery.",
  "You're so fat you don't have got cellulite, you've got celluheavy.",
  "You're so fat you influence the tides.",
  "You're so fat you jumped off the Grand Canyon and got stuck.",
  "You're so fat that you laid on the beach and Greenpeace tried to push you back in the water.",
  "You're so fat you leave footprints in concrete.",
  "You're so fat you need GPS to find your asshole.",
  "You're so fat you pull your pants down and your ass is still in them.",
  "You're so fat you show up on radar.",
  "If you were any less intelligent we'd have to water you three times a week..",
  "If your IQ was 3 points higher, you'd be a rock.",
  'I would insult you but nature did a better job.', 'Does your ass get jealous of all the shit that comes out of your mouth?', 'If I ate a bowl of alphabet soup, I could shit out a smarter sentence than any of yours.', "You're not pretty enough to be this stupid.",
  "That little voice in the back of your head, telling you you'll never be good enough? It's right.",
  "You look like you're going to spend your life having one epiphany after another, always thinking you've finally figured out what's holding you back, and how you can finally be productive and creative and turn your life around. But nothing will ever change. That cycle of mediocrity isn't due to some obstacle. It's who you *are*. The thing standing in the way of your dreams is; that the person having them is *you*.",
  'May your day and future be as pleasant as you are.', 'I would agree with you but then we would both be wrong.', 'I bite my thumb at you, sir.', "I'd call you a tool, but that would imply you were useful in at least one way.",
  'I hope you outlive your children.', 'Are you and your dick having a competition to see who can disappoint me the most?', 'Yo mamma is so ugly her portraits hang themselves.', 'Your birth certificate is an apology from the abortion clinic.', "If you were anymore inbred you'd be a sandwich.",
  'Say hello to your wife and my kids for me.', 'You are thick-headed bastards with a bloated bureaucracy, designed to compensate for your small and poor self-esteem, cocksuckers. You have the brains to ban the person who has come to support channel your bot, accusing him of violating the ephemeral ephemeral rules, stupid morons. By the way i have one of the biggest server(5.5k  people, ~30 anytime voiceonline members), and i know something about managing, and of these rules - dont be an asshole. You are fucking asshole, maybe it is product of your life alone, or your life with your mom, anyway - you are retard and your soul is a fucking bunch of stupid self-esteems.'];

class Command {
  async messageListener(msg) {
    if (msg.content.indexOf('https://old.reddit') !== -1) {
      const randomElement = insults[Math.floor(Math.random() * insults.length)];
      msg.reply(randomElement);
    }
  }

  getCommands() {
    return [];
  }
}

module.exports = Command;
